### ISSUE TITLE
Quem está fazendo o quê

### ISSUE THREAD

**Issue by alvelvis** [alvelvis/Documenta-o-UD-PT#1]
**Estrutura:**

- \chapter{}
    - \section{}
        - \subsection{}
            - \subsubsection{}

**Esqueleto:**

- [x] Formato UD
    - [x] Princípios
    - [x] Colunas/anotações
    - [x] Manipulação em Python
- [x] Lemas (lemma)
- [x] Classes gramaticais (upos)
    - [x] Verbos auxiliares
        - [x] Verbos de ligação
        - [x] Verbo *ser* como voz passiva
        - [x] Locuções verbais de tempo composto
        - [x] Locuções verbais aspectuais/modais não existem no UD
        - [x] Proposta de anotação para as locuções verbais aspectuais/modais
        - [x] Isso *foi* nos Estados Unidos: verbo *ser* como verbo pleno
        - [x] Não são locuções verbais: dois verbos plenos
    - [x] Formas participiais: verbo ou adjetivo?
        - [x] Formas participiais que são adjetivo
        - [x] Formas participiais que são verbo
        - [x] Casos difíceis das formas participiais
    - [x] Numerais
        - [x] Números compostos
        - [x] *R$ 50*: quem é o pai?
        - [x] *50% das pessoas*: quem é o pai?
        - [x] *Primeiro* lugar: adjetivo ou numeral?
    - [x] Pronomes substantivos, pronomes adjetivos e artigos
        - [x] Pronomes interrogativos
        - [x] Pronomes demonstrativos
        - [x] Pronomes relativos
        - [x] Pronomes indefinidos
        - [x] *A mais querida*, *O que eu sei*: pronome ou artigo?
    - [x] Preposições
        - [x] Princípio de classes dinâmicas
    - [x] Conjunções
        - [x] Conjunções coordenativas
        - [x] Conjunções subordinativas
        - [x] Advérbios interrogativos
- [x] Atributos morfológicos (feats)
- [x] Dependências (dephead e deprel)
    - [x] Núcleo da oração
    - [x] Coordenações
    - [x] Parataxis (parataxis)
    - [x] Sujeito da oração
        - [x] Caso o sujeito seja nominal (nsubj)
        - [x] Caso o sujeito seja oracional (csubj)
    - [x] Predicativos (acl ou xcomp?)
        - [x] *Pintou a modelo nua*: predicativo do objeto que é subordinado ao objeto
        - [x] *Declarou o réu culpado*: predicativo do objeto que é subordinado ao verbo
    - [x] Argumentos do verbo
        - [x] Caso o argumento do verbo seja nominal (obj, iobj)
        - [x] Caso o argumento do verbo seja oracional (ccomp, xcomp)
    - [x] Adjunto do verbo
        - [x] Caso seja advérbio (advmod -- indicar que pode modificar ADV, ADJ e VERB (e NOUN? rsrs))
        - [x] Caso seja nome (obl -- indicar que pode modificar ADV, ADJ e VERB (e NOUN? rsrs))
        - [x] Caso seja verbo (advcl -- só pode modificar VERB)
        - [x] Teve uma relação extraconjugal com **Monica** Lewinsky
    - [x] Adjuntos e argumentos do substantivo
        - [x] Adjunto adnominal
        - [x] Complemento nominal
        - [x] Aposto (appos)
            - [x] Orações com ", o que"
            - [x] Apostos coordenados
    - [x] Argumentos do adjetivo
    - [x] Locuções verbais
    - [x] Voz passiva
    - [x] Discurso direto
    - [x] Estruturas comparativas
    - [x] Particípio
    - [x] Elementos discursivos
        - [x] É que
        - [x] Como / tal como
        - [ ] Sim e não
    - [ ] Pontuação

**Comment by alvelvis** [comment]
- [x] Comecei a fazer a seção `Verbos auxiliares`.
EDIT: Terminei! É necessário revisar as listas de verbos auxiliares, pois elas podem indicar inconsistências no corpus que devem ser corrigidas.

Tati, que tal começar pela subseção `É que`?

**Comment by alvelvis** [comment]
- [x] Fazendo agora: a seção NUMERAIS.

**Comment by claudiafreitas** [comment]
- Pontuação deve ser a última seção.
- Incluir os princípios UD na página Inicial 
- Criar seção "Elementos Discursivos"

Texto:
Segundo as diretivas, frases que começam com "feedback words" como sim ou não, e a oração principal continua em seguida, tem o sim/não anotados como ADV (pos) e discourse (deprel). 

> Sim, porque as pessoas acabam por passar por todas, apesar das diferenças.
> 
> Sim, embora a abertura dos portos não esteja sendo feita impunemente.

O elemento root será o predicado da oração principal, e o elemento discourse apontará para ele. 

A combinação "é que", em construções como *exemplo* também é anotada como discourse (cf. seção xx)

**Comment by alvelvis** [comment]
Terminei os numerais! @claudiafreitas , pode verificar se a hierarquia da seção "Elementos discursivos" ficou boa? Aqui mesmo, no issue, onde eu coloquei os checklists.

**Comment by tatianashc** [comment]
- [x] Fazendo agora: SUJEITO DA ORAÇÃO

**Comment by tatianashc** [comment]
Terminada a seção SUJEITO DA ORAÇÃO.
- [x] Próxima: ADJUNTO ADVERBIAL.

**Comment by alvelvis** [comment]
- [x] Lembrete para mim: gerar as tabelas novamente com os dados atualizados da versão 2.5 do Bosque-UD.

- [x] Verficar todas as ocorrências de Xxx no final para substituir pela \fullref das seções.

- [x] Refiz agora a seção de verbos auxiliares levando em conta a discussão com o pessoal do UD

- [x] Fazendo agora: princípios UD

- [x] Locuções verbais (dependência)

- [x] Pronomes substantivos, pronomes adjetivos, interrogativos, artigos e determinantes

**Comment by tatianashc** [comment]
- [x] @alvelvis Linkar "ser como voz passiva" p/ seção voz passiva

**Comment by alvelvis** [comment]
Colocamos os nomes dos deprel nos títulos das seções para nos guiar, mas não é para inclui-los no documento.

**Comment by alvelvis** [comment]
- [x] Dentro da seção de nmod, apontar para o caso "ter relação com alguém" (que estará dentro da seção do obl)

**Comment by tatianashc** [comment]
Terminada a seção de adjunto adverbial

**Comment by alvelvis** [comment]
- [x] Adjuntos e argumentos do substantivo

**Comment by alvelvis** [comment]
@tatianashc , a gente tinha criado subsubsections{} pros adjuntos/argumentos do nome (caso seja NOUN, ADJ, NUM, etc.), mas eu desfiz, porque realmente não precisa, olha como ficou ótimo sem as subseções:

![image](https://user-images.githubusercontent.com/41649292/68057349-60deef00-fcd4-11e9-8365-232e2acf4f82.png)

**Comment by alvelvis** [comment]
- [x] Adicionar na seção de preposições: Quando há uma preposição (ADP), como nos casos acima, ela irá depender do nome que está à direita, e a relação será de case. DEste modo, a relação nmod se estabelece entre os dois nomes, e não entre um nome e uma preposição. 

- [x] Na seção de coordenações, falar da coordenação de apostos (linkar para aposto, porque são apostos, não conjs \fullref{sec:apostoscoordenados})

**Comment by alvelvis** [comment]
Ajeitar:
- [x] \subsubsection não aparecem no sumário da documentação :(
- [x] mudar header das páginas que têm o nome dos autores --> vira o nome do capítulo
- [ ] mudar fonte das \fullref (discriminar quando é figura, quando é dep, quando é seção)

**Comment by alvelvis** [comment]
Fazendo:
- [x] Argumentos do adjetivo

**Comment by alvelvis** [comment]
Fazendo:
- [x] Argumentos do verbo

**Comment by alvelvis** [comment]
@tatianashc , vamos mudar:
- [ ] Adjuntos do verbo
        - [ ] Adjunto adverbial
        - [ ]  Caso seja advérbio (advmod)
        - [ ]  Caso seja nome (obl)
        - [ ]  Caso seja verbo (advcl)

Por:
- [ ] Adjuntos do verbo
    - [ ]  Caso seja advérbio (advmod)
    - [ ]  Caso seja nome (obl)
    - [ ]  Caso seja verbo (advcl)

O único adjunto do verbo é o adverbial?

**Comment by silveira26aline** [comment]
Fazendo agora: Conjunções coordenativas

**Comment by silveira26aline** [comment]
- [x] Fazendo agora: Conjunções

**Comment by tatianashc** [comment]
> @tatianashc , a gente tinha criado subsubsections{} pros adjuntos/argumentos do nome (caso seja NOUN, ADJ, NUM, etc.), mas eu desfiz, porque realmente não precisa, olha como ficou ótimo sem as subseções:
> 
> ![image](https://user-images.githubusercontent.com/41649292/68057349-60deef00-fcd4-11e9-8365-232e2acf4f82.png)

Ficou ótimo mesmo! Será que faço a mesma coisa nas seções de sujeito e adjunto adverbial?

**Comment by tatianashc** [comment]
Será que não valeria a pena fazer uma seção de "Coordenações", em vez de "Orações Coordenadas"? Senão, onde colocamos os nomes coordenados? (Além disso, não fizemos uma seção pra orações subordinadas...)

**Comment by tatianashc** [comment]
Fazendo:
- [x] Voz passiva

**Comment by alvelvis** [comment]
> 
> 
> Será que não valeria a pena fazer uma seção de "Coordenações", em vez de "Orações Coordenadas"? Senão, onde colocamos os nomes coordenados? (Além disso, não fizemos uma seção pra orações subordinadas...)

De acordo. E que tal linkar "coordenações", em deprel, pra "Conjunções coordenativas", em upos? (seção que a @silveira26aline está fazendo agora) Daí é improtante que a seção "conjunções coordenativas" seja bastante completa, com "conj"s nominais e oracionais.

**Comment by alvelvis** [comment]
O que vamos fazer até 8/11:

Elvis:
- [x] argumentos do verbo
- [x] lemma
- [x] predicativos
- [x] parataxis
- [x] pontuação

Aline @silveira26aline :
- [x] Conjunções
- [x] coordenações
- [x] estruturas comparativas
- [x] preposições
- [x] núcleo da oração

Tati @tatianashc :
- [x] formas participais
- [x] particípio
- [x] elementos discursivos
- [x] discurso direto

**Comment by tatianashc** [comment]
@alvelvis Tenho bastante material de "é que" sem ser MWE pra colocar na seção de ccomp. Te passo?

**Comment by silveira26aline** [comment]
@alvelvis
- [x] Gerar listas, no formato padrão, de conjunções coordenativas e subordinativas. Caminho dessas listas: 

Interrogatório - busca 5 token.upos == "CCONJ" and token.deprel == "cc" já salva - distribuição por lema

Interrogatório - busca 5 token.upos == "SCONJ" and token.deprel == "mark" já salva - distribuição por lema

Ah! É importante fazer uma tabela pra conjunções que forem palavras únicas e outra tabela para MWEs. Isso significa que serão quatro tabelas: duas de coordenativas e duas para subordinativas

**Comment by alvelvis** [comment]
- [x] Na parte de classes dinâmicas, indicar:
- CLASSE É DADA PELO CONTEXTO: NÃO EXISTE PREPOSIÇÃO ESTÁTICA
- exceto: cconj, que é sempre cconj/cc, tomando o "e" como caso prototípico
- decisão provisória e consistente

**Comment by alvelvis** [comment]
- [x] Em "Formas participiais", quais são as referências do PROPOR 2018 e Dissert Luiza?
